### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by death667b** [AnomalyInnovations/serverless-stack-demo-client#10]
## What is happening:
When posting a new note on /notes/new a alert error is displayed 'SyntaxError: Unexpected end of JSON input'.
No note is posted to AWS

## What is expected to happen:
Note is posted to AWS without error

## Steps to reproduce
In ./src/libs/awsLib.js -> Function invokeApi
If the return has results.json() on the end the error will display.  Removing .json() will post the note.

However, if .json() is remove when displaying the default route (./src/containers/Home.js) then the web app fails with error 'Unhandled Rejection (TypeError): Cannot read property 'trim' of undefined'

**Comment by jayair** [comment]
@death667b Hmmm I don't think I could reproduce it on my end. So I suspect the issue might be with the create note API. Can you check the console for what is returned when calling `/notes/new`? Both the response body and headers?

**Comment by death667b** [comment]
Hrmm..  I am missing data

`{ status: 200, statusText: 'OK', data: '' }`

**Comment by death667b** [comment]
@jayair Thanks for the suggestion to look at the create note API.  I had a type in `callback(null, success(params.Item));`.

I had typed `params.items` - missing the capital I
