### ISSUE TITLE
Direct URL input or bookmarking notes on cloud front error

### ISSUE THREAD

**Issue by jatazoulja** [AnomalyInnovations/serverless-stack-demo-client#12]
I think this is more of a configuration issue.
https://hackathon.jatazoulja.com/article/5

This page isn’t working
hackathon.jatazoulja.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

I followed the steps here:
https://serverless-stack.com/chapters/create-a-cloudfront-distribution.html

**Comment by jayair** [comment]
@jatazoulja I've seen somebody come across this issue before. It's usually because it was not setup properly.

If you are setting it up for the link you posted. How come the http version (http://hackathon.jatazoulja.com/article/5) of that page doesn't work?

**Comment by jatazoulja** [comment]
Thanks @jayair 

I recreated everything from scratch. https://ignite.jatazoulja.com/article/11 should be working now. 

FYI, I had a CodeCamp a couple of weeks ago and uses your code base to introduce some of my coworker to AWS. **BIG thanks to that!**

**Comment by jayair** [comment]
@jatazoulja Thats awesome!
