### ISSUE TITLE
sourcemaps and debugging

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-demo-client#14]
Anyone found it hard to hit breakpoints or set them up in chrome with this version of create react app?

Ie see how some of these are greyed out

![image](https://user-images.githubusercontent.com/216566/31345691-7b6e9c48-ad0e-11e7-8c38-2624a72298a3.png)

**Comment by jayair** [comment]
Sadly I don't have enough experience with this. But out of curiosity, are you using the React Dev Tools extension?

**Comment by QuantumInformation** [comment]
I am, it seems to work most of the time, so closing.
