### ISSUE TITLE
[feature] amazon-cognito-identity-js has been replaced by AWS Amplify

### ISSUE THREAD

**Issue by ozbillwang** [AnomalyInnovations/serverless-stack-demo-client#29]
This demo gives a lot of help on how to use Cognito, but recently aws archived one sdk used in this demo: `amazon-cognito-identity-js` and move on with AWS Amplify. 

https://github.com/aws/amazon-cognito-identity-js

>Amazon Cognito Identity SDK for JavaScript

>NOTE: We have discontinued developing this library as part of this GitHub repository. We will continue to develop it as part of the **AWS Amplify** GitHub repository. You can still reach us by creating an issue on the AWS Amplify GitHub repository or posting to the Amazon Cognito Identity forums. Versions 1.x will still be available via NPM. Future development will continue on the 2.x versions.

Would you please change the codes to use AWS Amplify? 

Thanks.

**Comment by jayair** [comment]
@ozbillwang Not sure if you noticed the sign on all of our tutorial pages about this 😉

https://github.com/AnomalyInnovations/serverless-stack-com/issues/193
