### ISSUE TITLE
Syntax error: Unexpected token when trying asyncComponent

### ISSUE THREAD

**Issue by jforaker** [AnomalyInnovations/serverless-stack-demo-client#4]
Getting an error trying to run this... 

![image](https://cloud.githubusercontent.com/assets/2042031/26384314/7302a4b6-4006-11e7-967d-15726e47d83b.png)

`create-react-app` is up to date etc

**Comment by jayair** [comment]
@jforaker Can I see your package.json?

**Comment by jforaker** [comment]
Sure:

```
{
  "name": "stories",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.9.5"
  },
  "dependencies": {
    "history": "^4.6.1",
    "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-html-parser": "^1.0.3",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "serve": "latest",
    "whatwg-fetch": "^2.0.3"
  },
  "scripts": {
    "start": "NODE_ENV=production serve ./build --single",
    "dev": "PORT=5000 NODE_ENV=development react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "s3": "s3-upload"
  }
}
```

**Comment by jayair** [comment]
@jforaker Ah you need to upgrade `react-scripts`.

Run this `npm install --save-dev --save-exact react-scripts@1.0.6`.

**Comment by jayair** [comment]
Closing this.

**Comment by EwertonFontes** [comment]
I`m have this same issue.  Can you help me @jayair?
This is the package.json

{
  "name": "dashboard",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "react-scripts": "1.0.6"
  },
  "author": "Ewerton Fontes",
  "license": "Commercial",
  "homepage": "",
  "dependencies": {
    "axios": "^0.16.1",
    "chart.js": "^1.1.1",
    "create-react-class": "^15.5.3",
    "css-loader": "^0.23.1",
    "express": "^4.13.4",
    "highcharts": "^5.0.3",
    "moment": "^2.18.1",
    "prop-types": "^15.5.10",
    "raven-js": "^2.3.0",
    "rc-pagination": "^1.8.2",
    "react": "^15.5.4",
    "react-addons-css-transition-group": "^15.3.2",
    "react-addons-transition-group": "^15.3.2",
    "react-burger-menu": "^2.0.2",
    "react-chartjs": "^0.8.0",
    "react-datepicker": "^0.44.0",
    "react-day-picker": "^5.2.0",
    "react-dom": "^15.5.4",
    "react-highcharts": "^11.0.0",
    "react-maskedinput": "^3.3.4",
    "react-modal-bootstrap": "^1.1.1",
    "react-overlays": "^0.6.12",
    "react-popup": "^0.7.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.0",
    "react-router-redux": "^4.0.4",
    "react-scripts": "^0.7.0",
    "react-select": "^1.0.0-rc.3",
    "react-skylight": "^0.4.1",
    "react-transform-catch-errors": "^1.0.2",
    "react-transform-hmr": "^1.0.4",
    "reactstrap": "^3.9.0",
    "redbox-react": "^1.2.3",
    "redux": "^3.5.2",
    "redux-logger": "^3.0.1",
    "redux-saga": "^0.12.1",
    "reduxsauce": "^0.4.1",
    "rimraf": "^2.5.2",
    "style-loader": "^0.13.1",
    "styled-components": "^2.0.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.0.0",
    "underscore": "^1.8.3",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.0",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-hot-middleware": "^2.10.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "dev": "react-scripts start",
    "build": "react-scripts build",
    "test": "jest",
    "eject": "react-scripts eject"
  }
}

**Comment by jayair** [comment]
@EwertonFontes Yeah, it looks like your `react-scripts` is out of date as well.

Did you try upgrading it? Run this `npm install --save-dev --save-exact react-scripts@1.0.7`.

**Comment by EwertonFontes** [comment]
@jayair  I updated the react-scripts before and now again, but I`m getting the same problem

**Comment by jayair** [comment]
@EwertonFontes Your `package.json` shows that `react-scripts` is still the old version - `"react-scripts": "^0.7.0",`. Make sure you are running that command in your project root.

**Comment by EwertonFontes** [comment]
When I updated react-scripts the problem change to this :
> react-scripts: command not found! 

So I executed this commands:
> npm install -g npm@latest  //(to update npm because it is sometimes buggy.)
> rm -rf node_modules //to remove the existing modules.
> npm install //to re-install the project dependencies.

And the problem was solved!
Thanks very much @jayair !

**Comment by jayair** [comment]
@EwertonFontes Thanks for reporting back.
