### ISSUE TITLE
Why is the routes.js in the browser different to the one in the repo?

### ISSUE THREAD

**Issue by SoreGums** [AnomalyInnovations/serverless-stack-demo-client#47]
See the screenshot - does all this Async magic get rejigged around on the fly or something?

![image](https://user-images.githubusercontent.com/317/54079482-2a69f380-4342-11e9-8c87-baf61ebce924.png)

**Comment by jayair** [comment]
Isn't this the same as the one in the repo?

https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/src/Routes.js

**Comment by SoreGums** [comment]
it is lol - I'm sure I have seen an AsyncComponent in a repo like in the tutorials - will see where i've taken a right turn instead of a left and get back to this issue.

**Comment by jayair** [comment]
We have multiple branches for different chapters. So that is probably what you saw. But master deployed to the demo app.

**Comment by SoreGums** [comment]
OK I see now

https://serverless-stack.com/chapters/code-splitting-in-create-react-app.html

So the [demo link](https://demo.serverless-stack.com/) on that page seems to use the code-spliting-branch as chunks show up in the network tab.

wonder why chrome shows a different routes.js then - without the AsyncComponents
