### ISSUE TITLE
[Question] post deploy script

### ISSUE THREAD

**Issue by jatazoulja** [AnomalyInnovations/serverless-stack-demo-client#7]
`"postdeploy": "aws cloudfront create-invalidation --distribution-id E1KTCKT9SOAHBW --paths '/*' && aws cloudfront create-invalidation --distribution-id E3MQXGQ47VCJB0 --paths '/*'",`

Why have 2 distribution ID?

**Comment by jayair** [comment]
@jatazoulja We are invalidating the cache for both the main CloudFront distribution and the www redirect one as well. I guess you could get by with just the main one if the www redirect never changes.

**Comment by jatazoulja** [comment]
Can you provide the settings for each CloudFront? and what's the difference of each?

TIA.

**Comment by jayair** [comment]
@jatazoulja These are all covered in the tutorial - http://serverless-stack.com. It's in the chapters where we deploy our React.js app.

**Comment by jatazoulja** [comment]
Thanks @jayair 

will just leave this here in any case:
http://serverless-stack.com/chapters/create-a-cloudfront-distribution.html

Cheers.
